#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Dialog module <iqSelectLanguageDialogProto>. 
Generated by the iqFramework module the wxFormBuider prototype dialog.
"""

import locale
import wx

from . import language_dlg_proto

import iq
from iq.util import log_func
from iq.util import global_func
from iq.util import lang_func

from iq.engine.wx import form_manager
from iq.engine.wx import wxbitmap_func

__version__ = (0, 1, 1, 1)

SUPPORTED_LANGUAGES2WXLANGUAGES = {
    lang_func.ENGLISH_LANGUAGE: wx.LANGUAGE_ENGLISH,
    lang_func.RUSSIAN_LANGUAGE: wx.LANGUAGE_RUSSIAN,
}

SUPPORTED_WXLANGUAGES2LANGUAGES = {wx_language : language for language, wx_language in SUPPORTED_LANGUAGES2WXLANGUAGES.items()}


class iqSelectLanguageDialog(language_dlg_proto.iqSelectLanguageDialogProto,
                             form_manager.iqFormManager):
    """
    Dialog.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        self.wx_languages = list(SUPPORTED_LANGUAGES2WXLANGUAGES.values())
        language_dlg_proto.iqSelectLanguageDialogProto.__init__(self, *args, **kwargs)
        self.SetIcon(icon=wx.Icon(wxbitmap_func.createIconBitmap('fatcow/language')))

    def init(self):
        """
        Init dialog.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images method.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        pass

    def onCancelButtonClick(self, event):
        """
        Handler of the <Cancel> button.
        """
        self.EndModal(wx.ID_CANCEL)
        event.Skip()

    def onOkButtonClick(self, event):
        """
        Handler of the <OK> button.
        """
        self.EndModal(wx.ID_OK)
        event.Skip()


class iqSelectTranslationLanguageDialog(language_dlg_proto.iqSelectTranslationLanguageDialogProto,
                                        form_manager.iqFormManager):
    """
    Dialog.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        self.wx_languages = list(SUPPORTED_LANGUAGES2WXLANGUAGES.values())
        language_dlg_proto.iqSelectTranslationLanguageDialogProto.__init__(self, *args, **kwargs)
        self.SetIcon(icon=wx.Icon(wxbitmap_func.createIconBitmap('fatcow/locale')))

    def init(self):
        """
        Init dialog.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images method.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        locale_language = locale.getlocale()[0][:2]
        self.from_language_list_box.SetLanguage(SUPPORTED_LANGUAGES2WXLANGUAGES.get(locale_language, wx.LANGUAGE_ENGLISH))

        self.to_language_list_box.SetLanguage(wx.LANGUAGE_ENGLISH)

    def onCancelButtonClick(self, event):
        """
        Handler of the <Cancel> button.
        """
        self.EndModal(wx.ID_CANCEL)
        event.Skip()

    def onOkButtonClick(self, event):
        """
        Handler of the <OK> button.
        """
        self.EndModal(wx.ID_OK)
        event.Skip()


def selectLanguageDialog(parent=None):
    """
    Select language dialog.

    :param parent: Parent window.
    :return: True/False.
    """
    dialog = None
    try:
        if parent is None:
            parent = global_func.getMainWin()

        dialog = iqSelectLanguageDialog(parent)
        dialog.init()
        result = dialog.ShowModal()
        dialog.Destroy()
        return result == wx.ID_OK
    except:
        if dialog:
            dialog.Destroy()
        log_func.fatal(u'Error open dialog <iqSelectLanguageDialog>')
    return False


def selectTranslationLanguageDialog(parent=None):
    """
    Select translation languages dialog.

    :param parent: Parent window.
    :return: (From language, To language).
    """
    selected_languages = (None, None)
    dialog = None
    try:
        if parent is None:
            parent = global_func.getMainWin()

        dialog = iqSelectTranslationLanguageDialog(parent)
        dialog.init()
        result = dialog.ShowModal()
        if result == wx.ID_OK:
            selected_languages = (SUPPORTED_WXLANGUAGES2LANGUAGES.get(dialog.from_language_list_box.GetLanguage(),
                                                                      lang_func.ENGLISH_LANGUAGE),
                                  SUPPORTED_WXLANGUAGES2LANGUAGES.get(dialog.to_language_list_box.GetLanguage(),
                                                                      lang_func.ENGLISH_LANGUAGE))
        dialog.Destroy()
        return selected_languages
    except:
        if dialog:
            dialog.Destroy()
        log_func.fatal(u'Error open dialog <iqSelectLanguageDialog>')
    return None, None
