#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Module <new_resource_dialog.py>. 
Generated by the iqFramework module the Glade prototype.
"""

import os
import os.path
import signal
import gi

gi.require_version('Gtk', '3.0')
import gi.repository.Gtk

from iq.util import log_func
from ....util import file_func
from ....util import res_func
from ....util import spc_func
from ....util import id_func
from .... import components

from iq.engine.gtk import gtk_handler
# from iq.engine.gtk import gtktreeview_manager
# from iq.engine.gtk import gtkwindow_manager

from . import select_component_menu

__version__ = (0, 0, 0, 1)


class iqNewResourceDialog(gtk_handler.iqGtkHandler):
    """
    Unknown class.
    """
    def __init__(self, *args, **kwargs):
        self.glade_filename = os.path.join(os.path.dirname(__file__), 'new_resource_dlg.glade')
        gtk_handler.iqGtkHandler.__init__(self, glade_filename=self.glade_filename,
                                          top_object_name='new_resource_dialog',  
                                          *args, **kwargs)
        self.res_filename = None
        self.resource = None

        self.component_menu = None

    def init(self, component_spc=None, component_name=None, res_filename=None):
        """
        Initialization dialog.

        :param component_spc: Resource component specification.
        :param component_name: Component name.
        :param res_filename: Resource filename.
        :return:
        """
        self.initImages()
        self.initControls()

        if component_spc:
            component_type = component_spc.get('type', '')
            if component_type:
                self.component_textCtrl.SetValue(component_type)
                icon = component_spc.get(spc_func.ICON_ATTR_NAME, None)
                if icon:
                    bmp = wxbitmap_func.createIconBitmap()
                    if bmp:
                        self.component_bitmap.SetBitmap(bmp)
        if component_name:
            self.name_textCtrl.SetValue(component_name)
        if res_filename:
            self.path_dirPicker.SetPath(os.path.dirname(res_filename))
        else:
            res_filename = self.genResFilename(component_name)
            if res_filename:
                self.path_dirPicker.SetPath(os.path.dirname(res_filename))
        if res_filename:
            self.res_filename = res_filename
        if component_spc:
            self.resource = copy.deepcopy(component_spc)
            if component_name:
                self.resource['name'] = component_name
            if not self.resource.get('guid', None):
                self.resource['guid'] = id_func.genGUID()

        self.ok_button.Enable(bool(component_spc) and bool(component_name) and bool(res_filename))

    def genResFilename(self, component_name):
        """
        Generate resource filename by component_name.

        :param component_name: Component name.
        :return: New resource filename or None if error.
        """
        if component_name:
            res_filename = os.path.join(file_func.getProjectPath(),
                                        component_name + res_func.RESOURCE_FILE_EXT)
            return res_filename
        return None

    def initImages(self):
        """
        Init images of controls on form.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        pass

    def onCancelButtonClicked(self, widget):
        """
        Button click <Cancel> handler.
        """
        self.res_filename = None
        self.resource = None

    def onOkButtonClicked(self, widget):
        """
        Button click <OK> handler.
        """
        self.res_filename = os.path.join(self.path_dirPicker.GetPath(),
                                         self.name_textCtrl.GetValue() + res_func.RESOURCE_FILE_EXT)

        component_type = self.component_textCtrl.GetValue()
        component_spc = components.findComponentSpc(component_type)
        self.resource = copy.deepcopy(component_spc)
        self.resource['name'] = self.name_textCtrl.GetValue().strip()
        if not self.resource.get('guid', None):
            self.resource['guid'] = id_func.genGUID()

    def onComponentButtonClicked(self, widget):
        """
        Component button click handler.
        """
        try:
            self.component_menu = select_component_menu.iqSelectComponentMenu()
            self.component_menu.init(parent=self, parent_component=None)
            self.component_menu.create(menuitem_handler=self.onSelectComponentMenuItem)

            self.component_button.PopupMenu(self.component_menu)
        except:
            log_func.fatal(u'Error component select button')


def openNewResourceDialog():
    """
    Open new_resource_dialog.

    :return: True/False.
    """
    result = False
    obj = None
    try:
        obj = iqNewResourceDialog()
        obj.init()
        obj.getGtkTopObject().run()
        result = True
    except:
        log_func.fatal(u'Error open window <new_resource_dialog>')

    if obj and obj.getGtkTopObject() is not None:
        obj.getGtkTopObject().destroy()
    return result                    


def createNewResource(parent=None, component_spc=None, component_name=None, res_filename=None):
    """
    Create new resource.

    :param parent: Parent frame.
    :param component_spc: Resource component specification.
    :param component_name: Component name.
    :param res_filename: Resource filename.
    :return: New resource filename or None if error or Cancel button pressed.
    """
    dlg = None
    try:
        dlg = iqNewResourceDialog(parent=parent)
        dlg.init(component_spc, component_name, res_filename)
        result = None
        if dlg.ShowModal() == wx.ID_OK:
            resource = spc_func.clearAllResourcesFromSpc(dlg.resource)
            if res_func.saveResourceText(dlg.res_filename, resource):
                result = dlg.res_filename
        dlg.Destroy()
        return result
    except:
        log_func.fatal(u'Error create new resource')
        if dlg:
            dlg.Destroy()
    return None
