#!/usr/bin/env python3
"""Generated by runtui RAD Designer — My Application."""

import sys
import os

# Add parent dir to path
# sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from runtui import (
    App, Button, Window,
)
from runtui.widgets.container import Container
from runtui.layout.absolute import AbsoluteLayout


class StartEditorApp(App):
    """Application: StartEditor Application."""

    def __init__(self) -> None:
        super().__init__(theme="nord")

    def on_ready(self) -> None:
        self.main_window = Window(
            title="Exit: Ctrl+Q",
            x=5, y=2, width=46, height=16,
        )

        content = Container()
        content._layout_manager = AbsoluteLayout()

        self.new_project_button = Button(x=3, y=2, width=40, height=1, text='New project', on_click=self.onNewButtonClick)
        content.add_child(self.new_project_button)

        self.run_project_button = Button(x=3, y=4, width=40, height=1, text='Run project', on_click=self.onRunButtonClick)
        content.add_child(self.run_project_button)

        self.debug_project_button = Button(x=3, y=6, width=40, height=1, text='Debug project', on_click=self.onDebugButtonClick)
        content.add_child(self.debug_project_button)

        self.external_tools_button = Button(x=3, y=8, width=40, height=1, text='External tools', on_click=self.onExternalToolsButtonClick)
        content.add_child(self.external_tools_button)

        self.help_button = Button(x=3, y=10, width=40, height=1, text='Help', on_click=self.onHelpButtonClick)
        content.add_child(self.help_button)

        self.exit_button = Button(x=3, y=12, width=40, height=1, text='Exit', on_click=self.onExitButtonClick)
        content.add_child(self.exit_button)

        self.main_window.set_content(content)
        self.add_window(self.main_window)

    def onDebugButtonClick(self) -> None:
        """TODO: Implement onDebugButtonClick."""
        pass

    def onExitButtonClick(self) -> None:
        """TODO: Implement onExitButtonClick."""
        pass

    def onExternalToolsButtonClick(self) -> None:
        """TODO: Implement onExternalToolsButtonClick."""
        pass

    def onHelpButtonClick(self) -> None:
        """TODO: Implement onHelpButtonClick."""
        pass

    def onNewButtonClick(self) -> None:
        """TODO: Implement onNewButtonClick."""
        pass

    def onRunButtonClick(self) -> None:
        """TODO: Implement onRunButtonClick."""
        pass


if __name__ == "__main__":
    app = StartEditorApp()
    app.run()
