#!/usr/bin/env python3
"""Generated by runtui RAD Designer — My Application."""

import sys
import os

# Add parent dir to path
#sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from runtui import (
    App, Button, Window,
)
from runtui.widgets.container import Container
from runtui.layout.absolute import AbsoluteLayout


class MyApplicationApp(App):
    """Application: My Application."""

    def __init__(self) -> None:
        super().__init__(theme="nord")

    def on_ready(self) -> None:
        self.main_window = Window(
            title="Main Window",
            x=5, y=2, width=46, height=10,
        )

        content = Container()
        content._layout_manager = AbsoluteLayout()

        self.new_button = Button(x=3, y=2, width=40, height=1, text='New', on_click=self.onNewButtonClick)
        content.add_child(self.new_button)

        self.run_prj_button = Button(x=3, y=4, width=40, height=1, text='Run project', on_click=self.onRunProjectButtonClick)
        content.add_child(self.run_prj_button)

        self.exit_button = Button(x=3, y=6, width=40, height=1, text='Exit', on_click=self.onExitButtonClick)
        content.add_child(self.exit_button)

        self.main_window.set_content(content)
        self.add_window(self.main_window)

    def onExitButtonClick(self) -> None:
        """TODO: Implement onExitButtonClick."""
        pass

    def onNewButtonClick(self) -> None:
        """TODO: Implement onNewButtonClick."""
        pass

    def onRunProjectButtonClick(self) -> None:
        """TODO: Implement onRunProjectButtonClick."""
        pass


if __name__ == "__main__":
    app = MyApplicationApp()
    app.run()
