#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Module <report_action_win.py>. 
Generated by the iqFramework module the Glade prototype.
"""

import os
import os.path
import signal
import gi

gi.require_version('Gtk', '3.0')
import gi.repository.Gtk

from iq.util import log_func

from iq.engine.gtk import gtk_handler
# from iq.engine.gtk import gtktreeview_manager
# from iq.engine.gtk import gtkwindow_manager

__version__ = (0, 0, 0, 1)


class iqReportActionWin(gtk_handler.iqGtkHandler):
    """
    Unknown class.
    """
    def __init__(self, *args, **kwargs):
        self.glade_filename = os.path.join(os.path.dirname(__file__), 'report_action_win.glade')
        gtk_handler.iqGtkHandler.__init__(self, glade_filename=self.glade_filename,
                                          top_object_name='report_action_win',  
                                          *args, **kwargs)
                                          
    def init(self):
        """
        Init form.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images of controls on form.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        pass

    def onPrintButtonClicked(self, widget):
        """
        """
        pass

    def onPreviewButtonClicked(self, widget):
        """
        """
        pass

    def onExportButtonClicked(self, widget):
        """
        """
        pass

    def onExitButtonClicked(self, widget):
        """
        """
        pass


def openReportActionWin():
    """
    Open report_action_win.

    :return: True/False.
    """
    result = False
    obj = None
    try:
        obj = iqReportActionWin()
        obj.init()
        obj.getGtkTopObject().run()
        result = True
    except:
        log_func.fatal(u'Error open window <report_action_win>')

    if obj and obj.getGtkTopObject() is not None:
        obj.getGtkTopObject().destroy()
    return result                    
