#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Module <start_py_window.py>. 
Generated by the iqFramework module the Glade prototype.
"""

import os
import os.path
import signal
import gi

gi.require_version('Gtk', '3.0')
import gi.repository.Gtk

from iq.util import log_func
from iq.util import lang_func
from ...dialog import dlg_func

from iq.engine.gtk import gtk_handler
# from iq.engine.gtk import gtktreeview_manager
# from iq.engine.gtk import gtkwindow_manager

from ..wx import wxfb_manager
from ...script import migrate_py
from .code_generator import gui_generator

from ...engine.gtk import stored_gtk_form_manager

__version__ = (0, 0, 0, 1)

_ = lang_func.getTranslation().gettext


class iqStartPyWindow(gtk_handler.iqGtkHandler,
                      stored_gtk_form_manager.iqStoredGtkFormsManager):
    """
    Start python module editor dialog.
    """
    def __init__(self, *args, **kwargs):
        self.glade_filename = os.path.join(os.path.dirname(__file__), 'start_py_win.glade')
        gtk_handler.iqGtkHandler.__init__(self, glade_filename=self.glade_filename,
                                          top_object_name='start_py_window',  
                                          *args, **kwargs)
        self.py_filename = None

        self.loadCustomProperties()

    def init(self):
        """
        Init form.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images of controls on form.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        is_wxfb_py = wxfb_manager.isWXFormBuilderFormPy(self.py_filename)
        is_adapted_wxfb_py = wxfb_manager.isAdaptedWXFormBuilderFormPy(self.py_filename)
        self.getGtkObject('adapt_wxfb_form_button').set_sensitive(is_wxfb_py)
        self.getGtkObject('gen_gui_py_button').set_sensitive(is_adapted_wxfb_py)

    def onDestroy(self, widget):
        """
        Destroy window handler.
        """
        self.saveCustomProperties()
        gi.repository.Gtk.main_quit()

    def onGenWxFBPyFormButtonClicked(self, widget):
        """
        Button click handler <Generate GUI module>.
        """
        result = gui_generator.gen(src_filename=self.py_filename, parent=self)

        if result:
            msg = u'Python generate by <%s> was successful' % self.py_filename
            dlg_func.openMsgBox(title=u'EDITOR', prompt_text=msg)
        else:
            msg = u'Python migrate <%s> ended unsuccessfully' % self.py_filename
            dlg_func.openErrBox(title=u'EDITOR', prompt_text=msg)
        self.getGtkTopObject().close()

    def onMigratePyButtonClicked(self, widget):
        """
        Button click handler <Migrate>.
        """
        result = migrate_py.migratePy(py_filename=self.py_filename)

        if result:
            msg = u'Python migrate <%s> was successful' % self.py_filename
            dlg_func.openMsgBox(title=u'EDITOR', prompt_text=msg)
        else:
            msg = u'Python migrate <%s> ended unsuccessfully' % self.py_filename
            dlg_func.openErrBox(title=u'EDITOR', prompt_text=msg)
        self.getGtkTopObject().close()

    def onAdaptWxFBProjectPyFormButtonClicked(self, widget):
        """
        Button click handler <Adapt wxFormBuilder form python module>.
        """
        result = wxfb_manager.adaptWXWFormBuilderPy(self.py_filename)

        if result:
            msg = u'Python adaptation of wxFormBuilder module <%s> was successful' % self.py_filename
            dlg_func.openMsgBox(title=u'EDITOR', prompt_text=msg)
        else:
            msg = u'Python adaptation of wxFormBuilder module <%s> ended unsuccessfully' % self.py_filename
            dlg_func.openErrBox(title=u'EDITOR', prompt_text=msg)
        self.getGtkTopObject().close()

    def onHelpButtonClicked(self, widget):
        """
        Button click handler <Help>.
        """
        self.getGtkTopObject().close()

    def onExitButtonClicked(self, widget):
        """
        Button click handler <Exit>.
        """
        self.getGtkTopObject().close()


def openStartPyWindow(parent=None, py_filename=None):
    """
    Open start python module editor dialog.

    :param parent: Parent form.
    :param py_filename: Python filename.
    :return: True/False.
    """
    result = False
    obj = None
    try:
        obj = iqStartPyWindow()
        obj.py_filename = py_filename
        new_title = _(u'Python module') + ' <%s>' % os.path.basename(py_filename)
        obj.getGtkTopObject().set_title(new_title)
        obj.init()
        obj.getGtkTopObject().run()
        result = True
    except:
        log_func.fatal(u'Error open window <start_py_window>')

    if obj and obj.getGtkTopObject() is not None:
        obj.getGtkTopObject().destroy()
    return result                    


def startPythonEditor(py_filename, *args, **kwargs):
    """
    Start python module editor.

    :param py_filename: Python filename.
    :return:
    """
    log_func.info(u'GTK library version: %s' % gi.__version__)

    result = False
    win = None
    try:
        win = iqStartPyWindow()
        win.py_filename = py_filename
        new_title = _(u'Python module') + ' <%s>' % os.path.basename(py_filename)
        win.getGtkTopObject().set_title(new_title)
        win.init()
        win.getGtkTopObject().show_all()
        result = True
    except:
        log_func.fatal(u'Error open window <start_py_window>')

    gi.repository.Gtk.main()

    if win and win.getGtkTopObject() is not None:
        win.getGtkTopObject().destroy()
    return result
