#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Module <start_wxfb_window.py>. 
Generated by the iqFramework module the Glade prototype.
"""

import os
import os.path
import signal
import gi

gi.require_version('Gtk', '3.0')
import gi.repository.Gtk

from iq.util import log_func
from iq.util import lang_func

from iq.engine.gtk import gtk_handler
# from iq.engine.gtk import gtktreeview_manager
# from iq.engine.gtk import gtkwindow_manager

from ...dialog import dlg_func

from ..wx import wxfb_manager

from ...engine.gtk import stored_gtk_form_manager

__version__ = (0, 0, 0, 1)

_ = lang_func.getTranslation().gettext


class iqStartWxFBWindow(gtk_handler.iqGtkHandler,
                        stored_gtk_form_manager.iqStoredGtkFormsManager):
    """
    Start wxFormBuilder project editor dialog.
    """
    def __init__(self, *args, **kwargs):
        self.glade_filename = os.path.join(os.path.dirname(__file__), 'start_wxfb_win.glade')
        gtk_handler.iqGtkHandler.__init__(self, glade_filename=self.glade_filename,
                                          top_object_name='start_wxfb_window',  
                                          *args, **kwargs)
        self.fbp_filename = None

        self.wxformbuilder_manager = wxfb_manager.iqWXFormBuilderManager()

        self.loadCustomProperties()

    def init(self):
        """
        Init form.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images of controls on form.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        pass

    def onDestroy(self, widget):
        """
        Destroy window handler.
        """
        self.saveCustomProperties()
        gi.repository.Gtk.main_quit()

    def onOpenWxFBProjectButtonClicked(self, widget):
        """
        Button click handler <Open>.
        """
        if os.path.exists(self.fbp_filename):
            self.wxformbuilder_manager.openProject(prj_filename=self.fbp_filename)
        else:
            dlg_func.openWarningBox(title=u'WARNING',
                                    prompt_text=u'wxFormBuilder project file <%s> not found' % self.fbp_filename)
        self.getGtkTopObject().close()

    def onMigrateWxFBProjectButtonClicked(self, widget):
        """
        Button click handler <Migrate>.
        """
        result = wxfb_manager.migrateWXFormBuilderProject(self.fbp_filename)
        if result:
            dlg_func.openMsgBox(title=u'EDITOR',
                                prompt_text=u'Migration wxFormBuilder project file <%s> was successful' % self.fbp_filename)
        else:
            dlg_func.openWarningBox(title=u'EDITOR',
                                    prompt_text=u'Migration wxFormBuilder project file <%s> ended unsuccessfully' % self.fbp_filename)
        self.getGtkTopObject().close()

    def onNewWxFBProjectButtonClicked(self, widget):
        """
        Button click handler <New>.
        """
        self.wxformbuilder_manager.createProject()
        self.getGtkTopObject().close()

    def onHelpButtonClicked(self, widget):
        """
        Button click handler <Help>.
        """
        self.getGtkTopObject().close()

    def onExitButtonClicked(self, widget):
        """
        Button click handler <Exit>.
        """
        self.getGtkTopObject().close()


def openStartWxfbWindow(parent=None, fbp_filename=None):
    """
    Open start wxFormBuilder project editor dialog.

    :param parent: Parent form.
    :param fbp_filename: wxFormBuilder project file name.
    :return: True/False
    """
    result = False
    obj = None
    try:
        obj = iqStartWxFBWindow()
        obj.fbp_filename = fbp_filename
        new_title = _(u'wxFormBuider project') + ' <%s>' % os.path.basename(fbp_filename)
        obj.getGtkTopObject().set_title(new_title)
        obj.init()
        obj.getGtkTopObject().run()
        result = True
    except:
        log_func.fatal(u'Error open window <start_wxfb_window>')

    if obj and obj.getGtkTopObject() is not None:
        obj.getGtkTopObject().destroy()
    return result                    


def startWxFormBuilderEditor(fbp_filename, *args, **kwargs):
    """
    Open start folder editor window.

    :param fbp_filename: wxFormBuilder project file name.
    :return: True/False.
    """
    log_func.info(u'GTK library version: %s' % gi.__version__)

    result = False
    win = None
    try:
        win = iqStartWxFBWindow()
        win.fbp_filename = fbp_filename
        new_title = _(u'wxFormBuider project') + ' <%s>' % os.path.basename(fbp_filename)
        win.getGtkTopObject().set_title(new_title)
        win.init()
        win.getGtkTopObject().show_all()
        result = True
    except:
        log_func.fatal(u'Error open window <start_wxfb_window>')

    gi.repository.Gtk.main()

    if win and win.getGtkTopObject() is not None:
        win.getGtkTopObject().destroy()
    return result
