#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Module <text_entry_dialog.py>. 
Generated by the iqFramework module the Glade prototype.
"""

import os
import os.path
import signal
import gi

gi.require_version('Gtk', '3.0')
import gi.repository.Gtk

from iq.util import log_func

from iq.engine.gtk import gtk_handler
# from iq.engine.gtk import gtktreeview_manager
# from iq.engine.gtk import gtkwindow_manager

__version__ = (0, 0, 0, 1)


class iqTextEntryDialog(gtk_handler.iqGtkHandler):
    """
    Text entry dialog class.
    """
    def __init__(self, *args, **kwargs):
        self.glade_filename = os.path.join(os.path.dirname(__file__), 'text_entry_dialog.glade')
        gtk_handler.iqGtkHandler.__init__(self, glade_filename=self.glade_filename,
                                          top_object_name='text_entry_dialog',  
                                          *args, **kwargs)
                                          
    def init(self):
        """
        Init form.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images of controls on form.
        """
        pass

    def initControls(self):
        """
        Init controls method.
        """
        pass

    def onCancelButtonClicked(self, widget):
        """
        """
        pass

    def onOkButtonClicked(self, widget):
        """
        """
        pass


def openTextEntryDialog():
    """
    Open text_entry_dialog.

    :return: True/False.
    """
    handler = None
    try:
        handler = iqTextEntryDialog()
        handler.init()
        handler.getGtkTopObject().show_all()
        return True
    except:
        log_func.fatal(u'Error open window <text_entry_dialog>')
    return False                    
