#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Data object find control prototype.
Generated by the iqFramework module the wxFormBuider prototype panel.
"""

import wx
from . import wx_findctrl_proto

import iq
from iq.util import log_func
from iq.util import global_func

from iq.engine.wx import panel_manager

__version__ = (0, 0, 0, 1)


class iqDataObjFindCtrlProto(wx_findctrl_proto.iqFindCtrlProto, panel_manager.iqPanelManager):
    """
    Data object find control prototype.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        wx_findctrl_proto.iqFindCtrlProto.__init__(self, *args, **kwargs)

        # All find data object identificators
        self.find_idents = None
        # Current found identificator in the list of found identificators
        self.find_ident_idx = 0

    def onFindButtonClick(self, event):
        """
        Find button event handler.
        """
        event.Skip()

    def onFindText(self, event):
        """
        Change find text.
        """
        self.find_idents = None
        event.Skip()
