#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Python panel generate functions.
"""

import inspect

from ....util import log_func

__version__ = (0, 0, 0, 1)


CREATE_PANEL_FUNC_BODY_FMT = u'''
def create%s(parent=None):
    \"\"\"
    Create panel.

    :param parent: Parent window.
    :return: Panel object or None if error.
    \"\"\"
    try:
        if parent is None:
            parent = global_func.getMainWin()

        panel = %s(parent)
        panel.init()
        return panel
    except:
        log_func.fatal(u'Error create panel <%s>')
    return None
'''


ADDPAGE_PANEL_FUNC_BODY_FMT = u'''
def add%sPage(parent=None):
    \"\"\"
    Add page.

    :param parent: Parent window.
    :return: True/False.
    \"\"\"
    try:
        if parent is None:
            parent = global_func.getMainWin()

        panel = create%s(parent)
        if panel:
            parent.addPage(panel)
        return True
    except:
        log_func.fatal(u'Error add panel page <%s>')
    return False
'''

GEN_PY_MODULE_FMT = u'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-

\"\"\"
Panel module <%s>. 
Generated by the iqFramework modulo the wxFormBuider prototype panel.
\"\"\"

import wx
from . import %s

import iq
from iq.util import log_func
from iq.util import global_func

from iq.engine.wx import panel_manager

__version__ = (0, 0, 0, 1)


class %s(%s.%s, panel_manager.iqPanelManager):
    \"\"\"
    Panel.
    \"\"\"
    def __init__(self, *args, **kwargs):
        \"\"\"
        Constructor.
        \"\"\"
        %s.%s.__init__(self, *args, **kwargs)

    def init(self):
        \"\"\"
        Init panel.
        \"\"\"
        self.initImages()
        self.initControls()

    def initImages(self):
        \"\"\"
        Init images method.
        \"\"\"
        pass

    def initControls(self):
        \"\"\"
        Init controls method.
        \"\"\"
        pass

%s
%s
%s
'''


def genPanelClassName(src_class_name):
    """
    Generate panel class name.

    :param src_class_name: Source panel prototype class name.
    :return: New panel class name.
    """
    dst_class_name = src_class_name
    dst_class_name = dst_class_name[:-9] if dst_class_name.endswith('Prototype') else dst_class_name
    dst_class_name = dst_class_name[:-5] if dst_class_name.endswith('Proto') else dst_class_name
    return dst_class_name


def genCreateFunctionBody(class_name):
    """
    Generate create function text body.

    :param class_name: Panel class name.
    :return: Function text body.
    """
    function_name = class_name[2:] if class_name.startswith('iq') else class_name
    frm_body_function = CREATE_PANEL_FUNC_BODY_FMT % (function_name, class_name, class_name)
    return frm_body_function


def genAddPageFunctionBody(class_name):
    """
    Generate add page function text body.

    :param class_name: Panel class name.
    :return: Function text body.
    """
    function_name = class_name[2:] if class_name.startswith('iq') else class_name
    frm_body_function = ADDPAGE_PANEL_FUNC_BODY_FMT % (function_name, class_name, class_name, class_name)
    return frm_body_function


def genPythonPanel(src_module, src_class_name):
    """
    Generation of the panel class text.

    :param src_module: Source module object.
    :param src_class_name: Source class name.
    :return: True/False.
    """
    log_func.info(u'Generate panel class ... START')

    dst_class_name = genPanelClassName(src_class_name)
    src_class = getattr(src_module, src_class_name)

    # Handlers
    src_class_methods = [getattr(src_class, var_name) for var_name in dir(src_class)]
    src_class_events = [method for method in src_class_methods if inspect.isfunction(method) and
                        method.__name__ != '__init__' and
                        'event' in method.__code__.co_varnames and
                        method.__code__.co_argcount == 2]

    # A way to get the source code from a function object+
    #                                                    v
    body_functions = u'\n'.join(
        [u'\n'.join(inspect.getsourcelines(class_method)[0]) for class_method in src_class_events])
    body_functions = body_functions.replace(u'\t', u'    ').replace(u'( ', u'(').replace(u' )', u')')
    log_func.info(u'Append method in class <%s>:' % dst_class_name)
    log_func.debug(body_functions)

    create_body_function = genCreateFunctionBody(dst_class_name)
    frm_body_function = genAddPageFunctionBody(dst_class_name)

    py_txt = GEN_PY_MODULE_FMT % (src_class_name,
                                  src_module.__name__,
                                  dst_class_name, src_module.__name__, src_class_name,
                                  src_module.__name__, src_class_name,
                                  body_functions,
                                  create_body_function,
                                  frm_body_function)
    log_func.info(u'Generate panel class ... STOP')
    return py_txt
