#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Python wizard generate functions.
"""

import inspect

from ....util import log_func

__version__ = (0, 1, 1, 1)


OPEN_WIZARD_FUNC_BODY_FMT = u'''
def open%s(parent=None, wizard_width=1000, wizard_height=-1):
    \"\"\"
    Open wizard.

    :param parent: Parent window.
    :param wizard_width: Wizard width.
    :param wizard_height: Wizard height.
    :return: True/False.
    \"\"\"
    wizard = None
    try:
        if parent is None:
            parent = global_func.getMainWin()

        wizard = %s(parent)
        wizard.init()
        # Set size wizard
        wizard.SetPageSize(wx.Size(wizard_width, wizard_height))
        wizard.FitToPage(wizard.m_pages[0])

        # Run wizard
        result = wizard.RunWizard(firstPage=wizard.m_pages[0])
        wizard.Destroy()
        return result == wx.ID_OK
    except:
        if wizard:
            wizard.Destroy()
        log_func.fatal(u'Error open wizard <%s>')
    return False
'''

GEN_PY_MODULE_FMT = u'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-

\"\"\"
Wizard module <%s>. 
Generated by the iqFramework module the wxFormBuider prototype wizard.
\"\"\"

import os.path
import wx
from . import %s

import iq
from iq.util import log_func
from iq.util import global_func

from iq.engine.wx import form_manager

__version__ = (0, 0, 0, 1)


class %s(%s.%s, form_manager.iqFormManager):
    \"\"\"
    Wizard.
    \"\"\"
    def __init__(self, *args, **kwargs):
        \"\"\"
        Constructor.
        \"\"\"
        %s.%s.__init__(self, *args, **kwargs)

        # Connect Events
        self.Bind(wx.adv.EVT_WIZARD_FINISHED, self.onFinished)
        self.Bind(wx.adv.EVT_WIZARD_HELP, self.onHelp)
        self.Bind(wx.adv.EVT_WIZARD_PAGE_CHANGED, self.onPageChanged)
        self.Bind(wx.adv.EVT_WIZARD_PAGE_CHANGING, self.onPageChanging)

        # Set page handlers
        # self.first_wizPage.onChanged = self.onSelectFirstPageChanged
        # self.first_wizPage.onChanging = self.onSelectFirstPageChanging
        # ...

    def init(self):
        \"\"\"
        Init wizard.
        \"\"\"
        self.initImages()
        self.initControls()

    def initImages(self):
        \"\"\"
        Init images method.
        \"\"\"
        # bmp_filename = os.path.join(os.path.dirname(__file__), 'wizard_image.png')
        # bmp = wx.Bitmap(bmp_filename, wx.BITMAP_TYPE_PNG)
        # self.SetBitmap(bitmap=bmp)
        pass

    def initControls(self):
        \"\"\"
        Init controls method.
        \"\"\"
        pass

    def onPageChanged(self, event):
        """
        Page changed handler.
        The page has just been changed (this event cannot be vetoed).
        """
        page = event.GetPage()
        if hasattr(page, 'onChanged'):
            return page.onChanged(event)
        event.Skip()

    def onPageChanging(self, event):
        """
        Page changing handler.
        The page is being changed (this event can be vetoed).
        """
        page = event.GetPage()
        if hasattr(page, 'onChanging'):
            return page.onChanging(event)
        event.Skip()

    def onFinished(self, event):
        """
        Finish button click handler.
        """
        event.Skip()

    def onHelp(self, event):
        """
        Help button click handler.
        """
        event.Skip()

%s
%s
'''


def genWizardClassName(src_class_name):
    """
    Generate wizard class name.

    :param src_class_name: Source wizard prototype class name.
    :return: New wizard class name.
    """
    dst_class_name = src_class_name
    dst_class_name = dst_class_name[:-9] if dst_class_name.endswith('Prototype') else dst_class_name
    dst_class_name = dst_class_name[:-5] if dst_class_name.endswith('Proto') else dst_class_name
    return dst_class_name


def genOpenFunctionBody(class_name):
    """
    Generate open function text body.

    :param class_name: Wizard class name.
    :return: Function text body.
    """
    function_name = class_name[2:] if class_name.startswith('iq') else class_name
    frm_body_function = OPEN_WIZARD_FUNC_BODY_FMT % (function_name, class_name, class_name)
    return frm_body_function


def genPythonWizard(src_module, src_class_name):
    """
    Generation of the wizard class text.

    :param src_module: Source module object.
    :param src_class_name: Source class name.
    :return: True/False.
    """
    log_func.info(u'Generate wizard class ... START')

    dst_class_name = genWizardClassName(src_class_name)
    src_class = getattr(src_module, src_class_name)

    # Handlers
    src_class_methods = [getattr(src_class, var_name) for var_name in dir(src_class)]
    src_class_events = [method for method in src_class_methods if inspect.isfunction(method) and
                        method.__name__ != '__init__' and
                        'OnIdle' not in method.__name__ and
                        'event' in method.__code__.co_varnames and
                        method.__code__.co_argcount == 2]

    # A way to get the source code from a function object+
    #                                                    v
    body_functions = u'\n'.join(
        [u'\n'.join(inspect.getsourcelines(class_method)[0]) for class_method in src_class_events])
    body_functions = body_functions.replace(u'\t', u'    ').replace(u'( ', u'(').replace(u' )', u')')
    log_func.info(u'Append method in class <%s>:' % dst_class_name)
    log_func.debug(body_functions)

    frm_body_function = genOpenFunctionBody(dst_class_name)

    py_txt = GEN_PY_MODULE_FMT % (src_class_name,
                                  src_module.__name__,
                                  dst_class_name, src_module.__name__, src_class_name,
                                  src_module.__name__, src_class_name,
                                  body_functions,
                                  frm_body_function)
    log_func.info(u'Generate wizard class ... STOP')
    return py_txt
