#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MenuBar module <iqMainMenubarProto>. 
Generated by the iqFramework module the wxFormBuider prototype menubar.
"""

import wx
from . import main_menubar_proto

import iq
from iq.util import log_func
from iq.util import global_func

from iq.engine.wx import menubar_manager

__version__ = (0, 0, 0, 1)


class iqMainMenubar(main_menubar_proto.iqMainMenubarProto, menubar_manager.iqMenuBarManager):
    """
    MenuBar.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        main_menubar_proto.iqMainMenubarProto.__init__(self, *args, **kwargs)

    def init(self):
        """
        Init menubar.
        """
        self.initImages()

    def initImages(self):
        """
        Init images method.
        """
        pass



def createMainMenubar():
    """
    Create menubar.

    :return: MenuBar object or None if error.
    """
    try:
        menubar = iqMainMenubar()
        menubar.init()
        return menubar
    except:
        log_func.fatal(u'Error create menubar <iqMainMenubar>')
    return None

