#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Dialog module <iqStartFolderDialogProto>. 
Generated by the iqFramework modulo the wxFormBuider prototype dialog.
"""

import os.path
import wx
from . import start_folder_dlg

import iq
from ...util import log_func
from ...util import global_func
from ...util import res_func
from ...util import lang_func
from ...engine.wx import wxbitmap_func

from ...dialog import dlg_func

from ...engine.wx import form_manager

from . import wxfb_manager
from ..jasper_report import jasperreport_manager
from ..lime_report import limereport_manager

from .res_editor import new_resource_dialog
from .res_editor import resource_editor

from ...engine.wx import stored_wx_form_manager

from ...project import prj

__version__ = (0, 0, 0, 1)

_ = lang_func.getTranslation().gettext


class iqStartFolderDialog(start_folder_dlg.iqStartFolderDialogProto,
                          form_manager.iqFormManager,
                          stored_wx_form_manager.iqStoredWxFormsManager):
    """
    Dialog.
    """
    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        start_folder_dlg.iqStartFolderDialogProto.__init__(self, *args, **kwargs)
        bmp = wxbitmap_func.createIconBitmap('fatcow/application_add')
        if bmp:
            self.SetIcon(icon=wx.Icon(bmp))

        self.folder_path = None

        self.loadCustomProperties()

    def init(self):
        """
        Init dialog.
        """
        self.initImages()
        self.initControls()

    def initImages(self):
        """
        Init images method.
        """
        bmp = wxbitmap_func.createIconBitmap('fatcow/resultset_next')
        self.run_bitmap.SetBitmap(bmp)

    def initControls(self):
        """
        Init controls method.
        """
        if self.folder_path:
            folder_basename = os.path.basename(self.folder_path)
            prj_basename = folder_basename + res_func.RESOURCE_FILE_EXT
            prj_filename = os.path.join(self.folder_path, prj_basename)
            self.run_button.Enable(os.path.exists(prj_filename))

    def onExitButtonClick(self, event):
        """
        Button click handler <Exit>.
        """
        self.EndModal(wx.ID_CANCEL)
        event.Skip()

    def createNewMenu(self):
        """
        Create New menu.

        :return: Menu object.
        """
        new_menu = wx.Menu()

        icon_bmp = wxbitmap_func.createIconBitmap('fatcow/plugin_add')
        menuitem_label = _(u'New resource')
        menuitem_id = wx.NewId()
        menuitem = wx.MenuItem(new_menu, menuitem_id, menuitem_label)
        menuitem.SetBitmap(icon_bmp)
        new_menu.Append(menuitem)
        self.Bind(wx.EVT_MENU, self.onNewResMenuItem, id=menuitem_id)
        new_menu.AppendSeparator()

        icon_bmp = wxbitmap_func.createIconBitmap('fatcow/application_form_edit')
        menuitem_label = _(u'New wxFormBuilder project')
        menuitem_id = wx.NewId()
        menuitem = wx.MenuItem(new_menu, menuitem_id, menuitem_label)
        menuitem.SetBitmap(icon_bmp)
        new_menu.Append(menuitem)
        self.Bind(wx.EVT_MENU, self.onNewWXFBMenuItem, id=menuitem_id)

        icon_bmp = wxbitmap_func.createIconBitmap('fatcow/report')
        menuitem_label = _(u'New JasperReport report')
        menuitem_id = wx.NewId()
        menuitem = wx.MenuItem(new_menu, menuitem_id, menuitem_label)
        menuitem.SetBitmap(icon_bmp)
        new_menu.Append(menuitem)
        self.Bind(wx.EVT_MENU, self.onNewJasperReportMenuItem, id=menuitem_id)

        icon_bmp = wxbitmap_func.createIconBitmap('fatcow/fruit_lime')
        menuitem_label = _(u'New LimeReport report')
        menuitem_id = wx.NewId()
        menuitem = wx.MenuItem(new_menu, menuitem_id, menuitem_label)
        menuitem.SetBitmap(icon_bmp)
        new_menu.Append(menuitem)
        self.Bind(wx.EVT_MENU, self.onNewLimeReportMenuItem, id=menuitem_id)

        return new_menu

    def onNewButtonClick(self, event):
        """
        Button click handler <New ...>.
        """
        try:
            menu = self.createNewMenu()
            self.PopupMenu(menu)
            menu.Destroy()
        except:
            log_func.fatal(u'Error New menu popup')
        event.Skip()

    def onNewResMenuItem(self, event):
        """
        Menu item handler <New resource>.
        """
        new_res_filename = os.path.join(self.folder_path,
                                        'default%d%s' % (wx.NewId(),
                                                         res_func.RESOURCE_FILE_EXT)) if self.folder_path else None
        res_filename = new_resource_dialog.createNewResource(parent=self, res_filename=new_res_filename)

        self.EndModal(wx.ID_OK)

        if res_filename is not None:
            resource_editor.openResourceEditor(res_filename=res_filename)

        event.Skip()

    def onNewWXFBMenuItem(self, event):
        """
        Menu item handler <New wxFormBuilder project>.
        """
        wxfb_manager.runWXFormBuilder()
        self.EndModal(wx.ID_OK)
        event.Skip()

    def onNewJasperReportMenuItem(self, event):
        """
        Menu item handler <New JasperReport project>.
        """
        new_basename = dlg_func.getTextEntryDlg(parent=self, title=_(u'NEW'),
                                                prompt_text=_(u'New JasperReport filename'))
        if new_basename:
            new_prj_filename = os.path.join(self.folder_path,
                                            new_basename + jasperreport_manager.JASPER_REPORT_PROJECT_FILE_EXT)
            if jasperreport_manager.createJasperReportProjectFile(new_prj_filename):
                dlg_func.openMsgBox(title=_(u'CREATE'),
                                    prompt_text=_(u'Create JasperReport file <%s>' % new_prj_filename))
                self.EndModal(wx.ID_OK)
                jasperreport_manager.runJasperReportEditor(filename=new_prj_filename)
            else:
                dlg_func.openWarningBox(title=_(u'ERROR'),
                                        prompt_text=_(u'Error create JasperReport file <%s>' % new_prj_filename))
                self.EndModal(wx.ID_OK)
        event.Skip()

    def onNewLimeReportMenuItem(self, event):
        """
        Menu item handler <New LimeReport project>.
        """
        new_basename = dlg_func.getTextEntryDlg(parent=self, title=_(u'NEW'),
                                                prompt_text=_(u'New LimeReport filename'))
        if new_basename:
            new_prj_filename = os.path.join(self.folder_path,
                                            new_basename + limereport_manager.LIME_REPORT_PROJECT_FILE_EXT)
            if limereport_manager.createLimeReportProjectFile(new_prj_filename):
                dlg_func.openMsgBox(title=_(u'CREATE'),
                                    prompt_text=_(u'Create LimeReport file <%s>' % new_prj_filename))
                self.EndModal(wx.ID_OK)
                limereport_manager.runLimeReportEditor(filename=new_prj_filename)
            else:
                dlg_func.openWarningBox(title=_(u'ERROR'),
                                        prompt_text=_(u'Error create LimeReport file <%s>' % new_prj_filename))
                self.EndModal(wx.ID_OK)
        event.Skip()

    def onRunButtonClick(self, event):
        """
        Button click handler <Run project>.
        """
        project_manager = prj.iqProjectManager()
        selected_prj_name = os.path.basename(self.folder_path) if self.folder_path else None
        project_manager.run(selected_prj_name)

        self.EndModal(wx.ID_OK)
        event.Skip()


def openStartFolderDialog(parent=None, folder_path=None):
    """
    Open dialog.

    :param parent: Parent window.
    :param folder_path: Folder path.
    :return: True/False.
    """
    if parent is None:
        parent = global_func.getMainWin()

    dialog = None
    try:
        dialog = iqStartFolderDialog(parent)
        dialog.folder_path = folder_path
        dialog.init()
        result = dialog.ShowModal() == wx.ID_OK
        dialog.saveCustomProperties()
        dialog.Destroy()
        return result
    except:
        if dialog:
            dialog.Destroy()
        log_func.fatal(u'Error open dialog <iqStartFolderDialog>')
    return False


def startFolderEditor(folder_path=None):
    """
    Start folder editor.

    :param folder_path: Folder path.
    :return: True/False.
    """
    log_func.info(u'wxPython version: %s' % wx.VERSION_STRING)

    app = wx.App()
    result = openStartFolderDialog(folder_path=folder_path)
    app.MainLoop()
    return result
