#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Object property identifiers.
"""

__version__ = (0, 0, 0, 1)

STRING_EDITOR = 0
TEXT_EDITOR = 1
INTEGER_EDITOR = 2
FLOAT_EDITOR = 3
CHOICE_EDITOR = 4
CHECKBOX_EDITOR = 5
MULTICHOICE_EDITOR = 6
STRINGLIST_EDITOR = 7
SCRIPT_EDITOR = 10
READONLY_EDITOR = 11
EXTERNAL_EDITOR = 19
CUSTOM_EDITOR = 20

COLOUR_EDITOR = 21
FONT_EDITOR = 22
POINT_EDITOR = 23
SIZE_EDITOR = 24
PASSWORD_EDITOR = 25
FILE_EDITOR = 26
DIR_EDITOR = 27
IMAGE_EDITOR = 28
DATE_EDITOR = 29

METHOD_EDITOR = 31
EVENT_EDITOR = 32

PASSPORT_EDITOR = 40
LIBICON_EDITOR = 41
FLAG_EDITOR = 42
